version: '3.8'

services:
<<<<<<< HEAD
  # Base de datos PostgreSQL
  database:
    image: postgres:15
    container_name: optica-database
=======
  database:
    image: postgres:15
    container_name: optica_danniels_db
>>>>>>> fix/mover-desliz-test
    environment:
      POSTGRES_DB: optica_danniels
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
<<<<<<< HEAD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
=======
>>>>>>> fix/mover-desliz-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
<<<<<<< HEAD
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d optica_danniels"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    restart: unless-stopped
    networks:
      - optica-network

  # Backend API Node.js
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: optica-backend
    env_file:
      - ./Backend/src/config/.env
    environment:
      # Override para Docker específicamente
      NODE_ENV: production
      DB_HOST: database
      HOST: database
      DB_USERNAME: admin
      PASSWORD: admin123
      DATABASE: optica_danniels
      FRONTEND_URL: http://OpticaDanniels.com
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
      - ./Backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - optica-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React + Nginx
=======
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - optica_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: optica_danniels_backend
    environment:
      - NODE_ENV=production
    env_file:
      - ./Backend/src/config/.env
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./Backend/uploads:/app/uploads
    networks:
      - optica_network
    restart: unless-stopped

>>>>>>> fix/mover-desliz-test
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: optica-frontend
=======
    container_name: optica_danniels_frontend
    environment:
      - NODE_ENV=production
>>>>>>> fix/mover-desliz-test
    env_file:
      - ./Frontend/.env
    ports:
      - "80:80"
    depends_on:
<<<<<<< HEAD
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - optica-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PgAdmin para administrar base de datos (opcional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: optica-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@optica.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - optica-network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
  pgadmin_data:
    driver: local

networks:
  optica-network:
    driver: bridge
    name: optica-network
=======
      - backend
    networks:
      - optica_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  optica_network:
    driver: bridge 
>>>>>>> fix/mover-desliz-test
