/**
 * Regiones y comunas de Chile con costos de envío.
 *
 * Costos calculados en relación a la ubicación de la tienda:
 *   Óptica Danniels — Av. Manuel Rodríguez 426, Chiguayante, Biobío
 *
 * Estructura: { codigo, nombre, comunas: [{ nombre, costoEnvio }] }
 * costoEnvio en CLP. 0 = gratis (retiro en tienda o misma comuna).
 */

const regiones = [
  {
    codigo: "XV",
    nombre: "Arica y Parinacota",
    comunas: [
      { nombre: "Arica", costoEnvio: 8990 },
      { nombre: "Camarones", costoEnvio: 9990 },
      { nombre: "General Lagos", costoEnvio: 9990 },
      { nombre: "Putre", costoEnvio: 9990 },
    ],
  },
  {
    codigo: "I",
    nombre: "Tarapacá",
    comunas: [
      { nombre: "Alto Hospicio", costoEnvio: 8990 },
      { nombre: "Camiña", costoEnvio: 9990 },
      { nombre: "Colchane", costoEnvio: 9990 },
      { nombre: "Huara", costoEnvio: 9990 },
      { nombre: "Iquique", costoEnvio: 8990 },
      { nombre: "Pica", costoEnvio: 9990 },
      { nombre: "Pozo Almonte", costoEnvio: 9990 },
    ],
  },
  {
    codigo: "II",
    nombre: "Antofagasta",
    comunas: [
      { nombre: "Antofagasta", costoEnvio: 7990 },
      { nombre: "Calama", costoEnvio: 8490 },
      { nombre: "María Elena", costoEnvio: 8990 },
      { nombre: "Mejillones", costoEnvio: 8490 },
      { nombre: "Ollagüe", costoEnvio: 9990 },
      { nombre: "San Pedro de Atacama", costoEnvio: 9990 },
      { nombre: "Sierra Gorda", costoEnvio: 9990 },
      { nombre: "Taltal", costoEnvio: 8490 },
      { nombre: "Tocopilla", costoEnvio: 8490 },
    ],
  },
  {
    codigo: "III",
    nombre: "Atacama",
    comunas: [
      { nombre: "Caldera", costoEnvio: 7490 },
      { nombre: "Chañaral", costoEnvio: 7490 },
      { nombre: "Copiapó", costoEnvio: 6990 },
      { nombre: "Diego de Almagro", costoEnvio: 7490 },
      { nombre: "Freirina", costoEnvio: 7490 },
      { nombre: "Huasco", costoEnvio: 7490 },
      { nombre: "Tierra Amarilla", costoEnvio: 7490 },
      { nombre: "Vallenar", costoEnvio: 6990 },
    ],
  },
  {
    codigo: "IV",
    nombre: "Coquimbo",
    comunas: [
      { nombre: "Andacollo", costoEnvio: 6490 },
      { nombre: "Canela", costoEnvio: 6990 },
      { nombre: "Combarbalá", costoEnvio: 6490 },
      { nombre: "Coquimbo", costoEnvio: 5990 },
      { nombre: "Illapel", costoEnvio: 6490 },
      { nombre: "La Higuera", costoEnvio: 6490 },
      { nombre: "La Serena", costoEnvio: 5990 },
      { nombre: "Los Vilos", costoEnvio: 5990 },
      { nombre: "Monte Patria", costoEnvio: 6490 },
      { nombre: "Ovalle", costoEnvio: 5990 },
      { nombre: "Paihuano", costoEnvio: 6490 },
      { nombre: "Punitaqui", costoEnvio: 6490 },
      { nombre: "Río Hurtado", costoEnvio: 6990 },
      { nombre: "Salamanca", costoEnvio: 6490 },
      { nombre: "Vicuña", costoEnvio: 6490 },
    ],
  },
  {
    codigo: "V",
    nombre: "Valparaíso",
    comunas: [
      { nombre: "Algarrobo", costoEnvio: 4990 },
      { nombre: "Cabildo", costoEnvio: 5490 },
      { nombre: "Calera", costoEnvio: 4990 },
      { nombre: "Calle Larga", costoEnvio: 4990 },
      { nombre: "Cartagena", costoEnvio: 4990 },
      { nombre: "Casablanca", costoEnvio: 4990 },
      { nombre: "Catemu", costoEnvio: 5490 },
      { nombre: "Concón", costoEnvio: 4990 },
      { nombre: "El Quisco", costoEnvio: 4990 },
      { nombre: "El Tabo", costoEnvio: 4990 },
      { nombre: "Hijuelas", costoEnvio: 5490 },
      { nombre: "Isla de Pascua", costoEnvio: 14990 },
      { nombre: "Juan Fernández", costoEnvio: 14990 },
      { nombre: "La Cruz", costoEnvio: 4990 },
      { nombre: "La Ligua", costoEnvio: 5490 },
      { nombre: "Limache", costoEnvio: 4990 },
      { nombre: "Llaillay", costoEnvio: 4990 },
      { nombre: "Los Andes", costoEnvio: 4990 },
      { nombre: "Nogales", costoEnvio: 5490 },
      { nombre: "Olmué", costoEnvio: 4990 },
      { nombre: "Panquehue", costoEnvio: 5490 },
      { nombre: "Papudo", costoEnvio: 5490 },
      { nombre: "Petorca", costoEnvio: 5490 },
      { nombre: "Puchuncaví", costoEnvio: 5490 },
      { nombre: "Putaendo", costoEnvio: 5490 },
      { nombre: "Quillota", costoEnvio: 4990 },
      { nombre: "Quilpué", costoEnvio: 4990 },
      { nombre: "Quintero", costoEnvio: 5490 },
      { nombre: "Rinconada", costoEnvio: 5490 },
      { nombre: "San Antonio", costoEnvio: 4990 },
      { nombre: "San Esteban", costoEnvio: 5490 },
      { nombre: "San Felipe", costoEnvio: 4990 },
      { nombre: "Santa María", costoEnvio: 5490 },
      { nombre: "Santo Domingo", costoEnvio: 4990 },
      { nombre: "Valparaíso", costoEnvio: 4990 },
      { nombre: "Villa Alemana", costoEnvio: 4990 },
      { nombre: "Viña del Mar", costoEnvio: 4990 },
      { nombre: "Zapallar", costoEnvio: 5490 },
    ],
  },
  {
    codigo: "RM",
    nombre: "Metropolitana de Santiago",
    comunas: [
      { nombre: "Alhué", costoEnvio: 4990 },
      { nombre: "Buin", costoEnvio: 3990 },
      { nombre: "Calera de Tango", costoEnvio: 3990 },
      { nombre: "Cerrillos", costoEnvio: 3990 },
      { nombre: "Cerro Navia", costoEnvio: 3990 },
      { nombre: "Colina", costoEnvio: 3990 },
      { nombre: "Conchalí", costoEnvio: 3990 },
      { nombre: "Curacaví", costoEnvio: 4490 },
      { nombre: "El Bosque", costoEnvio: 3990 },
      { nombre: "El Monte", costoEnvio: 4490 },
      { nombre: "Estación Central", costoEnvio: 3990 },
      { nombre: "Huechuraba", costoEnvio: 3990 },
      { nombre: "Independencia", costoEnvio: 3990 },
      { nombre: "Isla de Maipo", costoEnvio: 4490 },
      { nombre: "La Cisterna", costoEnvio: 3990 },
      { nombre: "La Florida", costoEnvio: 3990 },
      { nombre: "La Granja", costoEnvio: 3990 },
      { nombre: "La Pintana", costoEnvio: 3990 },
      { nombre: "La Reina", costoEnvio: 3990 },
      { nombre: "Lampa", costoEnvio: 4490 },
      { nombre: "Las Condes", costoEnvio: 3990 },
      { nombre: "Lo Barnechea", costoEnvio: 3990 },
      { nombre: "Lo Espejo", costoEnvio: 3990 },
      { nombre: "Lo Prado", costoEnvio: 3990 },
      { nombre: "Macul", costoEnvio: 3990 },
      { nombre: "Maipú", costoEnvio: 3990 },
      { nombre: "María Pinto", costoEnvio: 4490 },
      { nombre: "Melipilla", costoEnvio: 4490 },
      { nombre: "Ñuñoa", costoEnvio: 3990 },
      { nombre: "Padre Hurtado", costoEnvio: 3990 },
      { nombre: "Paine", costoEnvio: 4490 },
      { nombre: "Pedro Aguirre Cerda", costoEnvio: 3990 },
      { nombre: "Peñaflor", costoEnvio: 3990 },
      { nombre: "Peñalolén", costoEnvio: 3990 },
      { nombre: "Pirque", costoEnvio: 4490 },
      { nombre: "Providencia", costoEnvio: 3990 },
      { nombre: "Pudahuel", costoEnvio: 3990 },
      { nombre: "Puente Alto", costoEnvio: 3990 },
      { nombre: "Quilicura", costoEnvio: 3990 },
      { nombre: "Quinta Normal", costoEnvio: 3990 },
      { nombre: "Recoleta", costoEnvio: 3990 },
      { nombre: "Renca", costoEnvio: 3990 },
      { nombre: "San Bernardo", costoEnvio: 3990 },
      { nombre: "San Joaquín", costoEnvio: 3990 },
      { nombre: "San José de Maipo", costoEnvio: 4490 },
      { nombre: "San Miguel", costoEnvio: 3990 },
      { nombre: "San Pedro", costoEnvio: 4490 },
      { nombre: "San Ramón", costoEnvio: 3990 },
      { nombre: "Santiago", costoEnvio: 3990 },
      { nombre: "Talagante", costoEnvio: 3990 },
      { nombre: "Tiltil", costoEnvio: 4490 },
      { nombre: "Vitacura", costoEnvio: 3990 },
    ],
  },
  {
    codigo: "VI",
    nombre: "O'Higgins",
    comunas: [
      { nombre: "Chimbarongo", costoEnvio: 3990 },
      { nombre: "Codegua", costoEnvio: 3990 },
      { nombre: "Coinco", costoEnvio: 3990 },
      { nombre: "Coltauco", costoEnvio: 3990 },
      { nombre: "Doñihue", costoEnvio: 3990 },
      { nombre: "Graneros", costoEnvio: 3990 },
      { nombre: "La Estrella", costoEnvio: 4490 },
      { nombre: "Las Cabras", costoEnvio: 4490 },
      { nombre: "Litueche", costoEnvio: 4490 },
      { nombre: "Lolol", costoEnvio: 4490 },
      { nombre: "Machalí", costoEnvio: 3990 },
      { nombre: "Malloa", costoEnvio: 3990 },
      { nombre: "Marchigüe", costoEnvio: 4490 },
      { nombre: "Mostazal", costoEnvio: 3990 },
      { nombre: "Nancagua", costoEnvio: 3990 },
      { nombre: "Navidad", costoEnvio: 4490 },
      { nombre: "Olivar", costoEnvio: 3990 },
      { nombre: "Palmilla", costoEnvio: 4490 },
      { nombre: "Paredones", costoEnvio: 4490 },
      { nombre: "Peumo", costoEnvio: 3990 },
      { nombre: "Pichidegua", costoEnvio: 3990 },
      { nombre: "Pichilemu", costoEnvio: 4490 },
      { nombre: "Placilla", costoEnvio: 3990 },
      { nombre: "Pumanque", costoEnvio: 4490 },
      { nombre: "Quinta de Tilcoco", costoEnvio: 3990 },
      { nombre: "Rancagua", costoEnvio: 3490 },
      { nombre: "Rengo", costoEnvio: 3490 },
      { nombre: "Requínoa", costoEnvio: 3490 },
      { nombre: "San Fernando", costoEnvio: 3490 },
      { nombre: "San Vicente", costoEnvio: 3490 },
      { nombre: "Santa Cruz", costoEnvio: 3990 },
    ],
  },
  {
    codigo: "VII",
    nombre: "Maule",
    comunas: [
      { nombre: "Cauquenes", costoEnvio: 2990 },
      { nombre: "Chanco", costoEnvio: 2990 },
      { nombre: "Colbún", costoEnvio: 2990 },
      { nombre: "Constitución", costoEnvio: 2990 },
      { nombre: "Curepto", costoEnvio: 2990 },
      { nombre: "Curicó", costoEnvio: 2990 },
      { nombre: "Empedrado", costoEnvio: 2990 },
      { nombre: "Hualañé", costoEnvio: 2990 },
      { nombre: "Licantén", costoEnvio: 2990 },
      { nombre: "Linares", costoEnvio: 2990 },
      { nombre: "Longaví", costoEnvio: 2990 },
      { nombre: "Maule", costoEnvio: 2990 },
      { nombre: "Molina", costoEnvio: 2990 },
      { nombre: "Parral", costoEnvio: 2990 },
      { nombre: "Pelarco", costoEnvio: 2990 },
      { nombre: "Pelluhue", costoEnvio: 2990 },
      { nombre: "Pencahue", costoEnvio: 2990 },
      { nombre: "Rauco", costoEnvio: 2990 },
      { nombre: "Retiro", costoEnvio: 2990 },
      { nombre: "Río Claro", costoEnvio: 2990 },
      { nombre: "Romeral", costoEnvio: 2990 },
      { nombre: "Sagrada Familia", costoEnvio: 2990 },
      { nombre: "San Clemente", costoEnvio: 2990 },
      { nombre: "San Javier", costoEnvio: 2990 },
      { nombre: "San Rafael", costoEnvio: 2990 },
      { nombre: "Talca", costoEnvio: 2990 },
      { nombre: "Teno", costoEnvio: 2990 },
      { nombre: "Vichuquén", costoEnvio: 2990 },
      { nombre: "Villa Alegre", costoEnvio: 2990 },
      { nombre: "Yerbas Buenas", costoEnvio: 2990 },
    ],
  },
  {
    codigo: "XVI",
    nombre: "Ñuble",
    comunas: [
      { nombre: "Bulnes", costoEnvio: 1990 },
      { nombre: "Chillán", costoEnvio: 1990 },
      { nombre: "Chillán Viejo", costoEnvio: 1990 },
      { nombre: "Cobquecura", costoEnvio: 2490 },
      { nombre: "Coelemu", costoEnvio: 2490 },
      { nombre: "Coihueco", costoEnvio: 2490 },
      { nombre: "El Carmen", costoEnvio: 2490 },
      { nombre: "Ninhue", costoEnvio: 2490 },
      { nombre: "Ñiquén", costoEnvio: 2490 },
      { nombre: "Pemuco", costoEnvio: 2490 },
      { nombre: "Pinto", costoEnvio: 2490 },
      { nombre: "Portezuelo", costoEnvio: 2490 },
      { nombre: "Quillón", costoEnvio: 2490 },
      { nombre: "Quirihue", costoEnvio: 2490 },
      { nombre: "Ránquil", costoEnvio: 2490 },
      { nombre: "San Carlos", costoEnvio: 1990 },
      { nombre: "San Fabián", costoEnvio: 2490 },
      { nombre: "San Ignacio", costoEnvio: 2490 },
      { nombre: "San Nicolás", costoEnvio: 2490 },
      { nombre: "Treguaco", costoEnvio: 2490 },
      { nombre: "Yungay", costoEnvio: 2490 },
    ],
  },
  {
    codigo: "VIII",
    nombre: "Biobío",
    comunas: [
      { nombre: "Alto Biobío", costoEnvio: 2490 },
      { nombre: "Antuco", costoEnvio: 1990 },
      { nombre: "Arauco", costoEnvio: 1990 },
      { nombre: "Cabrero", costoEnvio: 1490 },
      { nombre: "Cañete", costoEnvio: 1990 },
      { nombre: "Chiguayante", costoEnvio: 0 },
      { nombre: "Concepción", costoEnvio: 0 },
      { nombre: "Contulmo", costoEnvio: 1990 },
      { nombre: "Coronel", costoEnvio: 990 },
      { nombre: "Curanilahue", costoEnvio: 1490 },
      { nombre: "Florida", costoEnvio: 1490 },
      { nombre: "Hualpén", costoEnvio: 0 },
      { nombre: "Hualqui", costoEnvio: 990 },
      { nombre: "Laja", costoEnvio: 1490 },
      { nombre: "Lebu", costoEnvio: 1990 },
      { nombre: "Los Álamos", costoEnvio: 1990 },
      { nombre: "Los Ángeles", costoEnvio: 1490 },
      { nombre: "Lota", costoEnvio: 990 },
      { nombre: "Mulchén", costoEnvio: 1490 },
      { nombre: "Nacimiento", costoEnvio: 1490 },
      { nombre: "Negrete", costoEnvio: 1490 },
      { nombre: "Penco", costoEnvio: 0 },
      { nombre: "Quilaco", costoEnvio: 1990 },
      { nombre: "Quilleco", costoEnvio: 1990 },
      { nombre: "San Pedro de la Paz", costoEnvio: 0 },
      { nombre: "San Rosendo", costoEnvio: 1490 },
      { nombre: "Santa Bárbara", costoEnvio: 1990 },
      { nombre: "Santa Juana", costoEnvio: 990 },
      { nombre: "Talcahuano", costoEnvio: 0 },
      { nombre: "Tirúa", costoEnvio: 1990 },
      { nombre: "Tomé", costoEnvio: 990 },
      { nombre: "Tucapel", costoEnvio: 1990 },
      { nombre: "Yumbel", costoEnvio: 1490 },
    ],
  },
  {
    codigo: "IX",
    nombre: "La Araucanía",
    comunas: [
      { nombre: "Angol", costoEnvio: 2990 },
      { nombre: "Carahue", costoEnvio: 2990 },
      { nombre: "Cholchol", costoEnvio: 2990 },
      { nombre: "Collipulli", costoEnvio: 2990 },
      { nombre: "Cunco", costoEnvio: 2990 },
      { nombre: "Curacautín", costoEnvio: 2990 },
      { nombre: "Curarrehue", costoEnvio: 3490 },
      { nombre: "Ercilla", costoEnvio: 2990 },
      { nombre: "Freire", costoEnvio: 2990 },
      { nombre: "Galvarino", costoEnvio: 2990 },
      { nombre: "Gorbea", costoEnvio: 2990 },
      { nombre: "Lautaro", costoEnvio: 2990 },
      { nombre: "Loncoche", costoEnvio: 2990 },
      { nombre: "Lonquimay", costoEnvio: 3490 },
      { nombre: "Los Sauces", costoEnvio: 2990 },
      { nombre: "Lumaco", costoEnvio: 2990 },
      { nombre: "Melipeuco", costoEnvio: 3490 },
      { nombre: "Nueva Imperial", costoEnvio: 2990 },
      { nombre: "Padre Las Casas", costoEnvio: 2990 },
      { nombre: "Perquenco", costoEnvio: 2990 },
      { nombre: "Pitrufquén", costoEnvio: 2990 },
      { nombre: "Pucón", costoEnvio: 2990 },
      { nombre: "Purén", costoEnvio: 2990 },
      { nombre: "Renaico", costoEnvio: 2990 },
      { nombre: "Saavedra", costoEnvio: 2990 },
      { nombre: "Temuco", costoEnvio: 2990 },
      { nombre: "Teodoro Schmidt", costoEnvio: 2990 },
      { nombre: "Toltén", costoEnvio: 2990 },
      { nombre: "Traiguén", costoEnvio: 2990 },
      { nombre: "Victoria", costoEnvio: 2990 },
      { nombre: "Vilcún", costoEnvio: 2990 },
      { nombre: "Villarrica", costoEnvio: 2990 },
    ],
  },
  {
    codigo: "XIV",
    nombre: "Los Ríos",
    comunas: [
      { nombre: "Corral", costoEnvio: 3990 },
      { nombre: "Futrono", costoEnvio: 3990 },
      { nombre: "La Unión", costoEnvio: 3490 },
      { nombre: "Lago Ranco", costoEnvio: 3990 },
      { nombre: "Lanco", costoEnvio: 3490 },
      { nombre: "Los Lagos", costoEnvio: 3490 },
      { nombre: "Máfil", costoEnvio: 3490 },
      { nombre: "Mariquina", costoEnvio: 3490 },
      { nombre: "Paillaco", costoEnvio: 3490 },
      { nombre: "Panguipulli", costoEnvio: 3990 },
      { nombre: "Río Bueno", costoEnvio: 3490 },
      { nombre: "Valdivia", costoEnvio: 3490 },
    ],
  },
  {
    codigo: "X",
    nombre: "Los Lagos",
    comunas: [
      { nombre: "Ancud", costoEnvio: 4990 },
      { nombre: "Calbuco", costoEnvio: 4490 },
      { nombre: "Castro", costoEnvio: 4990 },
      { nombre: "Chaitén", costoEnvio: 5990 },
      { nombre: "Chonchi", costoEnvio: 4990 },
      { nombre: "Cochamó", costoEnvio: 5490 },
      { nombre: "Curaco de Vélez", costoEnvio: 4990 },
      { nombre: "Dalcahue", costoEnvio: 4990 },
      { nombre: "Fresia", costoEnvio: 4490 },
      { nombre: "Frutillar", costoEnvio: 4490 },
      { nombre: "Futaleufú", costoEnvio: 5990 },
      { nombre: "Hualaihué", costoEnvio: 5490 },
      { nombre: "Llanquihue", costoEnvio: 4490 },
      { nombre: "Los Muermos", costoEnvio: 4490 },
      { nombre: "Maullín", costoEnvio: 4490 },
      { nombre: "Osorno", costoEnvio: 3990 },
      { nombre: "Palena", costoEnvio: 5990 },
      { nombre: "Puerto Montt", costoEnvio: 3990 },
      { nombre: "Puerto Octay", costoEnvio: 4490 },
      { nombre: "Puerto Varas", costoEnvio: 4490 },
      { nombre: "Puqueldón", costoEnvio: 4990 },
      { nombre: "Purranque", costoEnvio: 4490 },
      { nombre: "Puyehue", costoEnvio: 4490 },
      { nombre: "Queilén", costoEnvio: 4990 },
      { nombre: "Quellón", costoEnvio: 4990 },
      { nombre: "Quemchi", costoEnvio: 4990 },
      { nombre: "Quinchao", costoEnvio: 4990 },
      { nombre: "Río Negro", costoEnvio: 4490 },
      { nombre: "San Juan de la Costa", costoEnvio: 4490 },
      { nombre: "San Pablo", costoEnvio: 4490 },
    ],
  },
  {
    codigo: "XI",
    nombre: "Aysén",
    comunas: [
      { nombre: "Aysén", costoEnvio: 7990 },
      { nombre: "Chile Chico", costoEnvio: 8990 },
      { nombre: "Cisnes", costoEnvio: 8990 },
      { nombre: "Cochrane", costoEnvio: 8990 },
      { nombre: "Coyhaique", costoEnvio: 7990 },
      { nombre: "Guaitecas", costoEnvio: 9990 },
      { nombre: "Lago Verde", costoEnvio: 8990 },
      { nombre: "O'Higgins", costoEnvio: 9990 },
      { nombre: "Río Ibáñez", costoEnvio: 8990 },
      { nombre: "Tortel", costoEnvio: 9990 },
    ],
  },
  {
    codigo: "XII",
    nombre: "Magallanes",
    comunas: [
      { nombre: "Antártica", costoEnvio: 14990 },
      { nombre: "Cabo de Hornos", costoEnvio: 11990 },
      { nombre: "Laguna Blanca", costoEnvio: 10990 },
      { nombre: "Natales", costoEnvio: 9990 },
      { nombre: "Porvenir", costoEnvio: 10990 },
      { nombre: "Primavera", costoEnvio: 10990 },
      { nombre: "Punta Arenas", costoEnvio: 9990 },
      { nombre: "Río Verde", costoEnvio: 10990 },
      { nombre: "San Gregorio", costoEnvio: 10990 },
      { nombre: "Timaukel", costoEnvio: 11990 },
      { nombre: "Torres del Paine", costoEnvio: 10990 },
    ],
  },
];

export default regiones;

/**
 * Busca el costo de envío para una región y comuna dadas.
 * @returns {number|null} costo en CLP, null si no se encuentra
 */
export function obtenerCostoEnvio(regionNombre, comunaNombre) {
  const region = regiones.find(
    (r) => r.nombre === regionNombre || r.codigo === regionNombre,
  );
  if (!region) return null;

  const comuna = region.comunas.find((c) => c.nombre === comunaNombre);
  return comuna ? comuna.costoEnvio : null;
}

/**
 * Retorna solo los nombres de las regiones.
 */
export function obtenerRegiones() {
  return regiones.map((r) => ({ codigo: r.codigo, nombre: r.nombre }));
}

/**
 * Retorna las comunas de una región.
 */
export function obtenerComunas(regionNombre) {
  const region = regiones.find(
    (r) => r.nombre === regionNombre || r.codigo === regionNombre,
  );
  return region ? region.comunas : [];
}
